name: Release

on:
  release:
    types: [created]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build Release Version
      run: go build -ldflags "-s -w" ./...

    - name: Compress binary
      uses: svenstaro/upx-action@v2
      with:
        file: ngsw-rehash

    - name: Create Hash of release file
      run: shasum -a 256 ngsw-rehash

    - name: Upload release artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ngsw-rehash-linux-x86
        path: ./ngsw-rehash
